pipeline {
    agent any

    environment {
        POSTGRES_SECRET = credentials('jenkins-postgres-credentials')
        REPO_URL = 'https://github.com/hannazykava99/dqe-automation.git'
        PARQUET_PATH = "parquet_data"
    }

    stages {

        stage('Clean Workspace') {
            steps {
                deleteDir()
            }
        }

        stage('Clone directly into workspace') {
            steps {
                sh """
                echo "Workspace before clone:"
                pwd
                ls -la

                echo "Cloning repo into current workspace root..."
                git clone ${REPO_URL} .

                echo "Workspace after clone:"
                ls -R
                """
            }
        }

        stage('Install Dependencies') {
            steps {
                dir("PyTest DQ Framework") {
                    sh """
                    echo "Installing dependencies..."

                    python3 -m pip install --break-system-packages setuptools wheel
                    pip install --break-system-packages -r requirements.txt
                    """
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir("PyTest DQ Framework") {
                    sh """
                    echo "Running tests..."

                    pytest tests \
                        --db_host=host.containers.internal \
                        --db_port=5434 \
                        --db_name=mydatabase \
                        --db_user=$POSTGRES_SECRET_USR \
                        --db_password=$POSTGRES_SECRET_PSW \
                        --html=html_report/report.html \
                        --self-contained-html
                    """
                }
            }
        }
    }

    post {
        always {
            dir("PyTest DQ Framework") {
                archiveArtifacts artifacts: 'html_report/**', allowEmptyArchive: true

                publishHTML(target: [
                    allowMissing: true,
                    keepAll: true,
                    reportDir: 'html_report',
                    reportFiles: 'report.html',
                    reportName: 'HTML Test Report'
                ])
            }
        }
    }
}
